# Generated by Django 4.2.4 on 2023-11-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('due_number', models.IntegerField()),
                ('due_amount', models.IntegerField()),
                ('year_income', models.IntegerField()),
                ('month_income', models.IntegerField()),
                ('daily_income', models.IntegerField()),
                ('month_profit', models.IntegerField()),
                ('year_expense', models.IntegerField()),
                ('month_expense', models.IntegerField()),
                ('total_student', models.IntegerField()),
                ('total_parent', models.IntegerField()),
                ('total_boys', models.IntegerField()),
                ('total_girl', models.IntegerField()),
            ],
        ),
    ]
